name: Inject Secrets for GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject secrets into HTML
        run: |
          sed -i "s|__API_KEY__|${{ secrets.API_KEY }}|g" Index.html
          sed -i "s|__SHEET_ID__|${{ secrets.SHEET_ID }}|g" Index.html
          sed -i "s|__SHEET_NAME__|${{ secrets.SHEET_NAME }}|g" Index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # change if your site is in a folder
